name: MinecraftVisualProgramming
version: '1.0-SNAPSHOT'
main: io.github.artyom.MinecraftVisualProgramming
api-version: '1.21'
commands:
  code:
    permission: op
  variable:
    permission: op
  value:
    permission: op
